#!/usr/bin/env bash
# =============================================================================
# prod-migrate.sh — apply the full migration set to the production
# database safely. Run ON THE VPS inside the app checkout, BEFORE deploying
# the new code. Idempotent: safe to re-run.
#
#   Usage:  bash prod-migrate.sh
#
# Steps: backup -> TS migrations (ledger) -> numbered SQL files -> verify
#
# Migrations source of truth:
#   - TypeORM classes in apps/web/src/migrations/*.ts, listed in
#     src/migrations/index.ts. Their combined SQL is GENERATED by
#     apps/web/scripts/gen-ts-migrations-sql.ts into
#     apps/web/migrations/ts_migrations_combined.sql — never edit that file.
#   - Numbered SQL files apps/web/src/migrations/0*.sql (applied in name order).
# =============================================================================
set -euo pipefail

APP_DIR="/root/aaqarpluus"          # adjust to your checkout
M="${APP_DIR}/apps/web/src/migrations"
DB_SERVICE="db"                     # docker compose service holding postgres
TS="${APP_DIR}/apps/web/migrations/ts_migrations_combined.sql"

cd "${APP_DIR}"
echo "==> Pulling latest code"
git pull origin main || { echo "git pull failed — resolve and re-run"; exit 1; }

# Every numbered SQL file, in name order (006, 007, ...). Computed after the
# pull so newly added migrations are included.
FILES=$(cd "${M}" && ls 0*.sql | sort)

echo "==> Backup (non-negotiable)"
STAMP=$(date +%Y%m%d-%H%M)
docker compose exec -T "${DB_SERVICE}" pg_dump -U postgres -d property_crm -Fc \
  > "backup-property_crm-${STAMP}.dump"
ls -la "backup-property_crm-${STAMP}.dump"

echo "==> Applying TypeORM migrations (with ledger)"
test -f "${TS}" || { echo "ERROR: ${TS} missing — regenerate with apps/web/scripts/gen-ts-migrations-sql.ts"; exit 1; }
docker compose exec -T "${DB_SERVICE}" psql -U postgres -d property_crm \
  -v ON_ERROR_STOP=1 -f /dev/stdin < "${TS}"

echo "==> Applying numbered SQL migrations"
for f in ${FILES}; do
  echo "   - ${f}"
  docker compose exec -T "${DB_SERVICE}" psql -U postgres -d property_crm \
    -v ON_ERROR_STOP=1 -f /dev/stdin < "${M}/${f}"
done

echo "==> Verify"
docker compose exec -T "${DB_SERVICE}" psql -U postgres -d property_crm \
  -c "\d zatca_invoices" >/dev/null && echo "  zatca_invoices OK"
docker compose exec -T "${DB_SERVICE}" psql -U postgres -d property_crm \
  -t -A -c "SELECT typname FROM pg_type WHERE typname='payment_method'" >/dev/null \
  && echo "  payment_method enum OK"
docker compose exec -T "${DB_SERVICE}" psql -U postgres -d property_crm \
  -t -A -c "SELECT COUNT(*) FROM migrations" | grep -qE "[1-9]" && echo "  migrations ledger OK"

echo "==> Deploy the new code now:"
echo "    docker compose up -d --build web"
echo "==> Then smoke: mark a payment 'paid' -> receipt PDF with QR + invoice row"